--
-- PostgreSQL database dump
--

\restrict XvOd4bliNzefVDKno5asbBcySCZjqzVNgclZueTcfPe1XR68sRCDdfmuEsBqxoz

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-04-04 22:25:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16868)
-- Name: brand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brand (
    id_brand bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255) NOT NULL
);


ALTER TABLE public.brand OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16867)
-- Name: brand_id_brand_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.brand ALTER COLUMN id_brand ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brand_id_brand_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16877)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id_category bigint NOT NULL,
    name character varying(100),
    description character varying(255)
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16876)
-- Name: category_id_category_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16884)
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id_country bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255) NOT NULL
);


ALTER TABLE public.country OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16883)
-- Name: country_id_country_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id_country ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_country_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16893)
-- Name: entry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entry (
    entry_date date NOT NULL,
    quantity integer NOT NULL,
    unit_cost double precision NOT NULL,
    id_entry bigint NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT entry_quantity_check CHECK ((quantity >= 1))
);


ALTER TABLE public.entry OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16892)
-- Name: entry_id_entry_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entry ALTER COLUMN id_entry ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entry_id_entry_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16906)
-- Name: exit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exit (
    exit_date date NOT NULL,
    quantity integer NOT NULL,
    id_exit bigint NOT NULL,
    product_id bigint NOT NULL,
    reason_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT exit_quantity_check CHECK ((quantity >= 1))
);


ALTER TABLE public.exit OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16905)
-- Name: exit_id_exit_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exit ALTER COLUMN id_exit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exit_id_exit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16919)
-- Name: platform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.platform (
    id_platform bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.platform OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16918)
-- Name: platform_id_platform_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.platform ALTER COLUMN id_platform ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platform_id_platform_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16927)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    current_stock integer NOT NULL,
    price double precision NOT NULL,
    brand_id bigint NOT NULL,
    category_id bigint NOT NULL,
    id_product bigint NOT NULL,
    platform_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    name character varying(150) NOT NULL,
    image_url character varying(255),
    description character varying(255),
    CONSTRAINT product_current_stock_check CHECK ((current_stock >= 0))
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16926)
-- Name: product_id_product_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id_product ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_product_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16942)
-- Name: reason; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reason (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255),
    id_reason bigint NOT NULL
);


ALTER TABLE public.reason OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 24576)
-- Name: reason_id_reason_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reason ALTER COLUMN id_reason ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reason_id_reason_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16941)
-- Name: reason_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reason ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reason_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16950)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id_role bigint NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16949)
-- Name: role_id_role_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16958)
-- Name: supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier (
    country_id bigint,
    id_supplier bigint NOT NULL,
    phone character varying(20) NOT NULL,
    contact character varying(100),
    name character varying(100) NOT NULL,
    address character varying(255),
    email character varying(255) NOT NULL
);


ALTER TABLE public.supplier OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16957)
-- Name: supplier_id_supplier_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.supplier ALTER COLUMN id_supplier ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_id_supplier_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16972)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_role bigint NOT NULL,
    id_user bigint NOT NULL,
    phone character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16971)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4994 (class 0 OID 16868)
-- Dependencies: 220
-- Data for Name: brand; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.brand VALUES (3, 'Sony', 'Marca japonesa de hardware y software');
INSERT INTO public.brand VALUES (1, 'Microsoft', 'Empresa de Software, Y Hardware norteamericana');


--
-- TOC entry 4996 (class 0 OID 16877)
-- Dependencies: 222
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.category VALUES (1, 'Acción', 'Categoría para juegos de acción');
INSERT INTO public.category VALUES (2, 'Rol', 'juegos de estrategia y de turnos');


--
-- TOC entry 4998 (class 0 OID 16884)
-- Dependencies: 224
-- Data for Name: country; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.country VALUES (1, 'El Salvador', 'Pequeño pais de crentro-america');
INSERT INTO public.country VALUES (4, 'Mexico', 'pais de centro america');
INSERT INTO public.country VALUES (5, 'Albania', 'Pais arabe ');


--
-- TOC entry 5000 (class 0 OID 16893)
-- Dependencies: 226
-- Data for Name: entry; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.entry VALUES ('2026-03-30', 10, 50, 1, 1, 1);
INSERT INTO public.entry VALUES ('2026-03-30', 10, 70, 2, 1, 1);
INSERT INTO public.entry VALUES ('2026-03-30', 10, 70, 3, 1, 1);
INSERT INTO public.entry VALUES ('2026-03-30', 100, 70, 4, 1, 1);
INSERT INTO public.entry VALUES ('2026-03-30', 10, 70, 5, 1, 1);
INSERT INTO public.entry VALUES ('2026-04-03', 10, 10, 6, 1, 1);
INSERT INTO public.entry VALUES ('2026-04-03', 150, 140, 7, 1, 1);
INSERT INTO public.entry VALUES ('2026-04-03', 50, 150, 8, 11, 1);
INSERT INTO public.entry VALUES ('2026-04-03', 1, 1, 9, 5, 2);
INSERT INTO public.entry VALUES ('2026-04-03', 10, 10, 10, 7, 2);
INSERT INTO public.entry VALUES ('2026-04-04', 10, 150, 11, 9, 2);
INSERT INTO public.entry VALUES ('2026-04-04', 150, 1520, 12, 10, 2);
INSERT INTO public.entry VALUES ('2026-04-04', 140, 102, 13, 11, 2);
INSERT INTO public.entry VALUES ('2026-04-04', 10, 147, 14, 5, 2);
INSERT INTO public.entry VALUES ('2026-04-02', 10, 5, 15, 1, 1);


--
-- TOC entry 5002 (class 0 OID 16906)
-- Dependencies: 228
-- Data for Name: exit; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.exit VALUES ('2026-03-30', 25, 1, 1, 1, 1);
INSERT INTO public.exit VALUES ('2026-04-03', 15, 2, 1, 1, 1);
INSERT INTO public.exit VALUES ('2026-04-03', 150, 3, 1, 1, 1);
INSERT INTO public.exit VALUES ('2026-04-03', 30, 4, 1, 1, 1);
INSERT INTO public.exit VALUES ('2026-03-30', 1, 5, 1, 1, 1);
INSERT INTO public.exit VALUES ('2026-04-03', 12, 6, 1, 1, 2);
INSERT INTO public.exit VALUES ('2026-04-04', 1, 7, 11, 2, 2);
INSERT INTO public.exit VALUES ('2026-03-30', 1, 8, 1, 1, 1);


--
-- TOC entry 5004 (class 0 OID 16919)
-- Dependencies: 230
-- Data for Name: platform; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.platform VALUES (1, 'Xbox-Original', 'Primera Xbox en salir al mercado');
INSERT INTO public.platform VALUES (2, 'Snes', 'super nintendo');
INSERT INTO public.platform VALUES (3, 'nes ', 'nintendo de 8 bits');


--
-- TOC entry 5006 (class 0 OID 16927)
-- Dependencies: 232
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product VALUES (10, 10, 1, 1, 14, 1, 1, 'prueba', 'https://via.placeholder.com/150', 'hola');
INSERT INTO public.product VALUES (30, 59.99, 1, 1, 7, 1, 1, 'mario', 'https://cdn.mobygames.com/covers/808732-final-fantasy-j2me-front-cover.png', 'nada');
INSERT INTO public.product VALUES (20, 59.99, 1, 1, 8, 1, 1, 'mario', 'https://i.etsystatic.com/44630762/r/il/fad8eb/5108588459/il_1588xN.5108588459_mye9.jpg', 'bueno');
INSERT INTO public.product VALUES (30, 59.99, 1, 1, 9, 1, 1, 'mario', 'https://cdn.mobygames.com/covers/808732-final-fantasy-j2me-front-cover.png', 'prueba');
INSERT INTO public.product VALUES (200, 550, 1, 1, 10, 1, 1, 'gta', 'https://via.placeholder.com/150', 'casi');
INSERT INTO public.product VALUES (239, 50, 1, 1, 11, 1, 1, 'lugi', 'https://via.placeholder.com/150', 'cerca');
INSERT INTO public.product VALUES (31, 59.99, 1, 1, 5, 1, 1, 'Final Fantasy', 'https://cdn.mobygames.com/covers/808732-final-fantasy-j2me-front-cover.png', NULL);
INSERT INTO public.product VALUES (96, 59.99, 1, 1, 1, 1, 1, 'Final Fantasy', 'https://cdn.mobygames.com/covers/808732-final-fantasy-j2me-front-cover.png', NULL);
INSERT INTO public.product VALUES (50, 130, 3, 2, 15, 2, 1, 'chronotrigger', 'https://miro.medium.com/v2/resize:fit:4372/1*4zq1uUWKXxykZHfV-8PhOQ.jpeg', 'juego de rol por turnos');


--
-- TOC entry 5008 (class 0 OID 16942)
-- Dependencies: 234
-- Data for Name: reason; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.reason VALUES (1, 'Venta', 'Venta realizada de los productos del inventario', 1);
INSERT INTO public.reason VALUES (2, 'Prestamo', 'Prestamo realizada de los productos del inventario', 2);
INSERT INTO public.reason VALUES (4, 'Obsequio', 'Regalos ', 4);


--
-- TOC entry 5010 (class 0 OID 16950)
-- Dependencies: 236
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role VALUES (1, 'ADMIN', 'Administrador del sistema completo');
INSERT INTO public.role VALUES (2, 'USER', 'Usuario normal del sistema con acceso limitados');


--
-- TOC entry 5012 (class 0 OID 16958)
-- Dependencies: 238
-- Data for Name: supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.supplier VALUES (1, 1, '1748-1547', 'Departamento de ventas', 'Victor', 'Santa Ana', 'victor@mail.com');
INSERT INTO public.supplier VALUES (1, 2, '1234-1234', 'departamento de emergencias', 'alberto', 'santa ana ', 'victoral1987@gmail.com');


--
-- TOC entry 5014 (class 0 OID 16972)
-- Dependencies: 240
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (1, 1, '12345678', 'Victor', 'victor@mail.com', '123456');
INSERT INTO public.users VALUES (1, 2, '12345678', 'Victor2', 'victor2@mail.com', '$2a$10$0S25wRKu6s9C/8na4YuRieZxCg4yn094lpWQhH0ZSMuma0gpIWtn2');
INSERT INTO public.users VALUES (1, 4, '12345678', 'Victor3', 'victor3@mail.com', '$2a$10$5sFZg8mvemAPEUW7HTLwfO69M91DuCQZm8cl0vBtEhNF1vt5GTFje');
INSERT INTO public.users VALUES (2, 6, '12345678', 'Victor3', 'victor4@mail.com', '$2a$10$JhmjSZ32M/B8RAPbT7C4cumlZKuupWzVZy6H8kmofy17CTytsEpuS');
INSERT INTO public.users VALUES (2, 7, '12345678', 'Victor3', 'victor5@mail.com', '$2a$10$F7BQ46dzKR86F/cZzpQw5er7DSOc1HlNxOpeEcPKkQ2xMISfVP5tW');
INSERT INTO public.users VALUES (2, 8, '12345678', 'Victor3', 'victor6@mail.com', '$2a$10$v7C1WQX4E500ijuGIlY7z.J21hiQycti1shWxzkg45xGrPXgWSnL6');
INSERT INTO public.users VALUES (2, 12, '12345678', 'Victor3', 'victor8@mail.com', '$2a$10$612Cpj/6xSDC7RIvjXTbS.WPE2rGtyGHoSXXO37GQejbT/H558fNm');
INSERT INTO public.users VALUES (2, 13, '71234567', 'dasdas', 'dasd@mail.com', '$2a$10$71DpeyE0iYACxRY.QgHLHuxPUc8Xep7ao2IzpvrM2Ngl7JvXH0MFe');
INSERT INTO public.users VALUES (1, 14, '12345678', 'victro', 'vcitro@mail.com', '$2a$10$v/uuwEocu1hxGAkriBdsieFXngK2AyALEYp5vARllHQfH3tmdrNqK');


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 219
-- Name: brand_id_brand_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.brand_id_brand_seq', 3, true);


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 221
-- Name: category_id_category_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_id_category_seq', 2, true);


--
-- TOC entry 5023 (class 0 OID 0)
-- Dependencies: 223
-- Name: country_id_country_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.country_id_country_seq', 5, true);


--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 225
-- Name: entry_id_entry_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entry_id_entry_seq', 15, true);


--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 227
-- Name: exit_id_exit_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exit_id_exit_seq', 8, true);


--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 229
-- Name: platform_id_platform_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.platform_id_platform_seq', 5, true);


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 231
-- Name: product_id_product_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_product_seq', 15, true);


--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 241
-- Name: reason_id_reason_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reason_id_reason_seq', 4, true);


--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 233
-- Name: reason_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reason_id_seq', 4, true);


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 235
-- Name: role_id_role_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_role_seq', 2, true);


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 237
-- Name: supplier_id_supplier_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supplier_id_supplier_seq', 2, true);


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 239
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_user_seq', 14, true);


--
-- TOC entry 4810 (class 2606 OID 16875)
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (id_brand);


--
-- TOC entry 4812 (class 2606 OID 16882)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id_category);


--
-- TOC entry 4814 (class 2606 OID 16891)
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id_country);


--
-- TOC entry 4816 (class 2606 OID 16904)
-- Name: entry entry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entry
    ADD CONSTRAINT entry_pkey PRIMARY KEY (id_entry);


--
-- TOC entry 4818 (class 2606 OID 16917)
-- Name: exit exit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT exit_pkey PRIMARY KEY (id_exit);


--
-- TOC entry 4820 (class 2606 OID 16925)
-- Name: platform platform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.platform
    ADD CONSTRAINT platform_pkey PRIMARY KEY (id_platform);


--
-- TOC entry 4822 (class 2606 OID 16940)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id_product);


--
-- TOC entry 4824 (class 2606 OID 16948)
-- Name: reason reason_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reason
    ADD CONSTRAINT reason_pkey PRIMARY KEY (id);


--
-- TOC entry 4826 (class 2606 OID 16956)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id_role);


--
-- TOC entry 4828 (class 2606 OID 16970)
-- Name: supplier supplier_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_email_key UNIQUE (email);


--
-- TOC entry 4830 (class 2606 OID 16968)
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id_supplier);


--
-- TOC entry 4832 (class 2606 OID 16986)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4834 (class 2606 OID 16984)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4840 (class 2606 OID 17017)
-- Name: product fk1mtsbur82frn64de7balymq9s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES public.category(id_category);


--
-- TOC entry 4841 (class 2606 OID 17027)
-- Name: product fk2kxvbr72tmtscjvyp9yqb12by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk2kxvbr72tmtscjvyp9yqb12by FOREIGN KEY (supplier_id) REFERENCES public.supplier(id_supplier);


--
-- TOC entry 4842 (class 2606 OID 17022)
-- Name: product fk60b21tm6b337t7mb22uwv9v5t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk60b21tm6b337t7mb22uwv9v5t FOREIGN KEY (platform_id) REFERENCES public.platform(id_platform);


--
-- TOC entry 4837 (class 2606 OID 16997)
-- Name: exit fk6xsjk3vnkp7xfdspkjjl20b84; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fk6xsjk3vnkp7xfdspkjjl20b84 FOREIGN KEY (product_id) REFERENCES public.product(id_product);


--
-- TOC entry 4835 (class 2606 OID 16987)
-- Name: entry fk8mt2q5u6o7bx6isqprbgf7pt5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entry
    ADD CONSTRAINT fk8mt2q5u6o7bx6isqprbgf7pt5 FOREIGN KEY (product_id) REFERENCES public.product(id_product);


--
-- TOC entry 4845 (class 2606 OID 17037)
-- Name: users fkdd7mh9fv3g835kod5rfpdcvs9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkdd7mh9fv3g835kod5rfpdcvs9 FOREIGN KEY (id_role) REFERENCES public.role(id_role);


--
-- TOC entry 4844 (class 2606 OID 17032)
-- Name: supplier fkdp2i9p8sxew7tj0dksty5dw4t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT fkdp2i9p8sxew7tj0dksty5dw4t FOREIGN KEY (country_id) REFERENCES public.country(id_country);


--
-- TOC entry 4836 (class 2606 OID 16992)
-- Name: entry fkftvnb1ll0a4l98cgcif439dvp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entry
    ADD CONSTRAINT fkftvnb1ll0a4l98cgcif439dvp FOREIGN KEY (user_id) REFERENCES public.users(id_user);


--
-- TOC entry 4838 (class 2606 OID 17002)
-- Name: exit fkj2cv4skd2xee2c7ei70dk7an4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fkj2cv4skd2xee2c7ei70dk7an4 FOREIGN KEY (reason_id) REFERENCES public.reason(id);


--
-- TOC entry 4839 (class 2606 OID 17007)
-- Name: exit fkl1uelb2x7xp95ipnur134env8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fkl1uelb2x7xp95ipnur134env8 FOREIGN KEY (user_id) REFERENCES public.users(id_user);


--
-- TOC entry 4843 (class 2606 OID 17012)
-- Name: product fks6cydsualtsrprvlf2bb3lcam; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fks6cydsualtsrprvlf2bb3lcam FOREIGN KEY (brand_id) REFERENCES public.brand(id_brand);


-- Completed on 2026-04-04 22:25:44

--
-- PostgreSQL database dump complete
--

\unrestrict XvOd4bliNzefVDKno5asbBcySCZjqzVNgclZueTcfPe1XR68sRCDdfmuEsBqxoz

