--
-- PostgreSQL database dump
--

\restrict iIhyQP0mZdxXQy7dorMh7utCV2IgsYgj2GUJZOmrZhP79afIwoQ32pyx9QrcbbU

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-03-29 00:09:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16589)
-- Name: brand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brand (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.brand OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16588)
-- Name: brand_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16555)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id_category bigint NOT NULL,
    description character varying(255),
    name character varying(100)
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16554)
-- Name: category_id_category_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16597)
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.country OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16596)
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16605)
-- Name: entry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entry (
    id_entry bigint NOT NULL,
    entry_date date NOT NULL,
    quantity integer NOT NULL,
    unit_cost double precision NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT entry_quantity_check CHECK ((quantity >= 1))
);


ALTER TABLE public.entry OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16604)
-- Name: entry_id_entry_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entry ALTER COLUMN id_entry ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entry_id_entry_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16618)
-- Name: exit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exit (
    id_exit bigint NOT NULL,
    exit_date date NOT NULL,
    quantity integer NOT NULL,
    product_id bigint NOT NULL,
    reason_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT exit_quantity_check CHECK ((quantity >= 1))
);


ALTER TABLE public.exit OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16617)
-- Name: exit_id_exit_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exit ALTER COLUMN id_exit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exit_id_exit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16631)
-- Name: platform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.platform (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.platform OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16630)
-- Name: platform_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.platform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16639)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id_product bigint NOT NULL,
    name character varying(150) NOT NULL,
    price double precision NOT NULL,
    stock_actual integer NOT NULL,
    brand_id bigint NOT NULL,
    category_id bigint NOT NULL,
    platform_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    CONSTRAINT product_stock_actual_check CHECK ((stock_actual >= 0))
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16638)
-- Name: product_id_product_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id_product ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_product_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16654)
-- Name: reason; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reason (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.reason OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16653)
-- Name: reason_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reason ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reason_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16562)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id_role bigint NOT NULL,
    description character varying(255),
    name character varying(50) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16561)
-- Name: role_id_role_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16662)
-- Name: supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier (
    id_supplier bigint NOT NULL,
    address character varying(255),
    contact character varying(100),
    email character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    country_id bigint
);


ALTER TABLE public.supplier OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16661)
-- Name: supplier_id_supplier_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.supplier ALTER COLUMN id_supplier ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_id_supplier_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16570)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_user bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(10) NOT NULL,
    phone character varying(20) NOT NULL,
    id_role bigint NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16569)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4817 (class 2606 OID 16595)
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 16560)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id_category);


--
-- TOC entry 4819 (class 2606 OID 16603)
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- TOC entry 4821 (class 2606 OID 16616)
-- Name: entry entry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entry
    ADD CONSTRAINT entry_pkey PRIMARY KEY (id_entry);


--
-- TOC entry 4823 (class 2606 OID 16629)
-- Name: exit exit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT exit_pkey PRIMARY KEY (id_exit);


--
-- TOC entry 4825 (class 2606 OID 16637)
-- Name: platform platform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.platform
    ADD CONSTRAINT platform_pkey PRIMARY KEY (id);


--
-- TOC entry 4827 (class 2606 OID 16652)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id_product);


--
-- TOC entry 4829 (class 2606 OID 16660)
-- Name: reason reason_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reason
    ADD CONSTRAINT reason_pkey PRIMARY KEY (id);


--
-- TOC entry 4811 (class 2606 OID 16568)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id_role);


--
-- TOC entry 4831 (class 2606 OID 16672)
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id_supplier);


--
-- TOC entry 4813 (class 2606 OID 16582)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4833 (class 2606 OID 16674)
-- Name: supplier ukg7qiwwu4vpciysmeeyme9gg1d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT ukg7qiwwu4vpciysmeeyme9gg1d UNIQUE (email);


--
-- TOC entry 4815 (class 2606 OID 16580)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4840 (class 2606 OID 16705)
-- Name: product fk1mtsbur82frn64de7balymq9s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES public.category(id_category);


--
-- TOC entry 4841 (class 2606 OID 16715)
-- Name: product fk2kxvbr72tmtscjvyp9yqb12by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk2kxvbr72tmtscjvyp9yqb12by FOREIGN KEY (supplier_id) REFERENCES public.supplier(id_supplier);


--
-- TOC entry 4842 (class 2606 OID 16710)
-- Name: product fk60b21tm6b337t7mb22uwv9v5t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk60b21tm6b337t7mb22uwv9v5t FOREIGN KEY (platform_id) REFERENCES public.platform(id);


--
-- TOC entry 4837 (class 2606 OID 16685)
-- Name: exit fk6xsjk3vnkp7xfdspkjjl20b84; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fk6xsjk3vnkp7xfdspkjjl20b84 FOREIGN KEY (product_id) REFERENCES public.product(id_product);


--
-- TOC entry 4835 (class 2606 OID 16675)
-- Name: entry fk8mt2q5u6o7bx6isqprbgf7pt5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entry
    ADD CONSTRAINT fk8mt2q5u6o7bx6isqprbgf7pt5 FOREIGN KEY (product_id) REFERENCES public.product(id_product);


--
-- TOC entry 4834 (class 2606 OID 16583)
-- Name: users fkdd7mh9fv3g835kod5rfpdcvs9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkdd7mh9fv3g835kod5rfpdcvs9 FOREIGN KEY (id_role) REFERENCES public.role(id_role);


--
-- TOC entry 4844 (class 2606 OID 16720)
-- Name: supplier fkdp2i9p8sxew7tj0dksty5dw4t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT fkdp2i9p8sxew7tj0dksty5dw4t FOREIGN KEY (country_id) REFERENCES public.country(id);


--
-- TOC entry 4836 (class 2606 OID 16680)
-- Name: entry fkftvnb1ll0a4l98cgcif439dvp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entry
    ADD CONSTRAINT fkftvnb1ll0a4l98cgcif439dvp FOREIGN KEY (user_id) REFERENCES public.users(id_user);


--
-- TOC entry 4838 (class 2606 OID 16690)
-- Name: exit fkj2cv4skd2xee2c7ei70dk7an4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fkj2cv4skd2xee2c7ei70dk7an4 FOREIGN KEY (reason_id) REFERENCES public.reason(id);


--
-- TOC entry 4839 (class 2606 OID 16695)
-- Name: exit fkl1uelb2x7xp95ipnur134env8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fkl1uelb2x7xp95ipnur134env8 FOREIGN KEY (user_id) REFERENCES public.users(id_user);


--
-- TOC entry 4843 (class 2606 OID 16700)
-- Name: product fks6cydsualtsrprvlf2bb3lcam; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fks6cydsualtsrprvlf2bb3lcam FOREIGN KEY (brand_id) REFERENCES public.brand(id);


-- Completed on 2026-03-29 00:09:23

--
-- PostgreSQL database dump complete
--

\unrestrict iIhyQP0mZdxXQy7dorMh7utCV2IgsYgj2GUJZOmrZhP79afIwoQ32pyx9QrcbbU

